/**
 * generated by Xtext 2.16.0
 */
package org.php.ruler.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class RuleUiModule extends AbstractRuleUiModule {
  public RuleUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
