/*
* generated by Xtext
*/
package org.ruler;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ModellerStandaloneSetup extends ModellerStandaloneSetupGenerated{

	public static void doSetup() {
		new ModellerStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

