/*
 * generated by Xtext
 */
package org.ruler.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ModellerUiModule extends org.ruler.ui.AbstractModellerUiModule {
	public ModellerUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
