/*
 * generated by Xtext 2.16.0
 */
package org.php.ruler.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.php.ruler.RuleRuntimeModule
import org.php.ruler.RuleStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class RuleIdeSetup extends RuleStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new RuleRuntimeModule, new RuleIdeModule))
	}
	
}
