/*
 * generated by Xtext
 */
package org.ruler.ui.contentassist

import org.ruler.ui.contentassist.AbstractModellerProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ModellerProposalProvider extends AbstractModellerProposalProvider {
}
