/*
 * generated by Xtext 2.16.0
 */
package org.php.ruler


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class RuleStandaloneSetup extends RuleStandaloneSetupGenerated {

	def static void doSetup() {
		new RuleStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
